# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=64)),
                ('db_size_class', models.IntegerField()),
                ('db_relative_size_class', models.IntegerField()),
                ('db_weight_class', models.IntegerField()),
                ('db_value', models.IntegerField()),
                ('db_black_market_index', models.IntegerField()),
                ('db_tags', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='db_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.ItemCategory'),
        ),
    ]
