# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_character_id', models.IntegerField()),
                ('db_is_major_level', models.BooleanField()),
                ('db_level_taken', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
                ('db_is_force_sensitive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.IntegerField()),
                ('db_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=64)),
                ('db_value', models.IntegerField()),
                ('db_black_market_index', models.IntegerField()),
                ('db_tags', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=64)),
                ('db_size_class', models.IntegerField()),
                ('db_relative_size_class', models.IntegerField()),
                ('db_weight_class', models.IntegerField()),
                ('db_tags', models.CharField(max_length=512)),
                ('db_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RaceTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.IntegerField()),
                ('db_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TraitWordlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_ordinal', models.IntegerField()),
                ('db_value', models.CharField(max_length=32)),
                ('db_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait')),
            ],
        ),
        migrations.AddField(
            model_name='racetrait',
            name='db_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait'),
        ),
        migrations.AddField(
            model_name='race',
            name='db_traits',
            field=models.ManyToManyField(through='gamedb.RaceTrait', to='gamedb.Trait'),
        ),
        migrations.AddField(
            model_name='item',
            name='db_item_prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.ItemPrototype'),
        ),
        migrations.AddField(
            model_name='classtrait',
            name='db_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait'),
        ),
        migrations.AddField(
            model_name='class',
            name='db_traits',
            field=models.ManyToManyField(through='gamedb.ClassTrait', to='gamedb.Trait'),
        ),
        migrations.AddField(
            model_name='characterlevel',
            name='db_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Class'),
        ),
    ]
