# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
                ('db_is_force_sensitive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.IntegerField()),
                ('db_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RaceTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.IntegerField()),
                ('db_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TraitWordlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_ordinal', models.IntegerField()),
                ('db_value', models.CharField(max_length=32)),
                ('db_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait')),
            ],
        ),
        migrations.AddField(
            model_name='racetrait',
            name='db_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait'),
        ),
        migrations.AddField(
            model_name='classtraits',
            name='db_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Trait'),
        ),
    ]
