# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_body_part', models.CharField(max_length=16)),
                ('db_damage_type', models.CharField(max_length=16)),
                ('db_trigger_index', models.IntegerField()),
                ('db_status_effect', models.CharField(max_length=32)),
                ('db_status_duration', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='db_body_table',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
