# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='db_traits',
            field=models.ManyToManyField(to='gamedb.ClassTrait'),
        ),
    ]
