# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0002_auto_20160711_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_character_id', models.IntegerField()),
                ('db_is_major_level', models.BooleanField()),
                ('db_level_taken', models.IntegerField()),
                ('db_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedb.Class')),
            ],
        ),
        migrations.RenameModel(
            old_name='ClassTraits',
            new_name='ClassTrait',
        ),
    ]
