# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0002_auto_20160717_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_owner_id', models.IntegerField()),
                ('db_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_class_type', models.IntegerField()),
                ('db_name', models.CharField(max_length=32)),
                ('db_size_class', models.IntegerField()),
                ('db_relative_size_class', models.IntegerField()),
                ('db_weight_class', models.IntegerField()),
                ('db_part_size_class', models.IntegerField()),
            ],
        ),
    ]
