# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0003_auto_20160715_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='db_traits',
            field=models.ManyToManyField(through='gamedb.ClassTrait', to='gamedb.Trait'),
        ),
    ]
