# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedb', '0004_class_db_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='db_traits',
            field=models.ManyToManyField(through='gamedb.RaceTrait', to='gamedb.Trait'),
        ),
    ]
